package com.tom.webapp.model;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.personNum
     *
     * @mbggenerated
     */
    private Integer personnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.comId
     *
     * @mbggenerated
     */
    private Integer comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.id
     *
     * @return the value of tbl_dept.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.id
     *
     * @param id the value for tbl_dept.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.name
     *
     * @return the value of tbl_dept.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.name
     *
     * @param name the value for tbl_dept.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.personNum
     *
     * @return the value of tbl_dept.personNum
     *
     * @mbggenerated
     */
    public Integer getPersonnum() {
        return personnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.personNum
     *
     * @param personnum the value for tbl_dept.personNum
     *
     * @mbggenerated
     */
    public void setPersonnum(Integer personnum) {
        this.personnum = personnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.comId
     *
     * @return the value of tbl_dept.comId
     *
     * @mbggenerated
     */
    public Integer getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.comId
     *
     * @param comid the value for tbl_dept.comId
     *
     * @mbggenerated
     */
    public void setComid(Integer comid) {
        this.comid = comid;
    }
}